### PR TITLE
fix: Clean up code

### PR DESCRIPTION
**Pull request by maximus12793**
* Clean up misc comments
* Fix minor linter errors
* Fix unclosed file when reading keyword
* Default `dataflow_match_score` scoring logic to 0 (otherwise DMS will always be 1 which is not ideal for invalid matches)

**Note:** The original paper proposes   a default weighting of `0.1,0.1,0.4,0.4,`. Happy to make a PR for this or leave as-is.

### CODE REVIEW

**Comment by k4black** [comment]
Great! Thanks for the contribution! :3
Could you please check and fix the tests that failed now? 

Regarding default weights - I just copied it from the original repo, but your suggestion makes sense! Happy if you'll make PR (but please note the default values in README with paper ref)

**Comment by maximus12793** [comment]
Updated tests + added logging when applicable. So actually this scoring logic does seem OK due to the weighting scheme. (for standalone tests you could return none then validate but think its fine as-is).

Couldn't find the referenced `test_code_x_glue_readme_examples` but updated these based on my machines fp-precision.

**Comment by k4black** [comment]
@maximus12793 Here it is - an example from readme 
https://github.com/microsoft/CodeXGLUE/blob/main/Code-Code/code-to-code-trans/example.png

**Comment by maximus12793** [comment]
Hmm, yea unfortunately not sure how to repro those numbers for the second test or if they used different weights, language (`c_sharp`?) or what. Updated to pass linter, should be good for now!

**Pull request merged**
